version: '2.1'

services:

  postgres:
    build: ./app/src/db
    healthcheck:
      test: exit 0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  web:
    build: ./app
    volumes:
      - "./app:/src/app"
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/jobs_dev
      - DATABASE_URL_TEST=postgres://admin:admin@postgres:5432/jobs_test
      - NODE_ENV=dev
    depends_on:
      postgres:
        condition: service_healthy
    links:
     - postgres
