version: '2.1'

services:

  users-db:
    container_name: "users-db"
    build:
      context: ./services/users/src/db
      dockerfile: ./Dockerfile-users-db
    healthcheck:
      test: exit 0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=node_users_dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  users-service:
    container_name: 'users-service'
    build:
      context: ./services/users/.
      dockerfile: ./Dockerfile-users
    volumes:
      - "./services/users:/src/app"
      - "./services/users/package.json:/src/package.json"
    ports:
      - "3003:3003"
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
